import { Inter_Tight } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const inter_tight = Inter_Tight({
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased relative bg-white ${inter_tight.className} overflow-x-hidden`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
