import { Inter_Tight } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const inter_tight = Inter_Tight({
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-inter-tight",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter_tight.variable}>
      <body className="antialiased relative font-[var(--font-inter-tight)] bg-white">
        <Header />
        {children}
      </body>
    </html>
  );
}
